import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center justify-center h-screen text-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <main className="space-y-8">
        <h1 className="text-5xl font-bold">
          Welcome to <a href="https://nextjs.org" className="text-blue-11">Next.js!</a>
        </h1>

        <p className="text-lg">
          Get started by editing{' '}
          <code className="px-3 py-2 rounded-lg bg-gray-2">pages/index.tsx</code>
        </p>

        <p className="inline-block px-3 py-2 font-medium rounded-lg bg-blue-2 text-blue-12">
          Tailwind CSS and Radix Colors are installed. Inter is the default font.
        </p>

        <div className="grid auto-cols-[100] grid-cols-2 grid-rows-2 gap-8">
          <a href="https://nextjs.org/docs" className="px-5 py-5 text-left transition-all border-2 rounded-lg w-72 w-120 border-gray-6 hover:border-gray-7">
            <h2 className="pb-2 text-xl font-bold">Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="px-5 py-5 text-left transition-all border-2 rounded-lg w-72 w-120 border-gray-6 hover:border-gray-7">
            <h2 className="pb-2 text-xl font-bold">Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="px-5 py-5 text-left transition-all border-2 rounded-lg w-72 w-120 border-gray-6 hover:border-gray-7"
          >
            <h2 className="pb-2 text-xl font-bold">Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="px-5 py-5 text-left transition-all border-2 rounded-lg w-72 w-120 border-gray-6 hover:border-gray-7"
          >
            <h2 className="pb-2 text-xl font-bold">Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="pt-12">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
